name: Create GitHub Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call_tests:
    uses: ./.github/workflows/tests.yml

  create_release:
    runs-on: ubuntu-latest
    needs: call_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application JAR for release
        run: make package-release

      - name: Extract project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create a GitHub release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          files: target/uview-${{ env.VERSION }}.jar
